db_file			"~/.mpd/database"
log_file			"~/.mpd/log"
state_file			"~/.mpd/state"

music_directory "~/music"
playlist_directory "~/music/playlists"
auto_update "yes"

bind_to_address "127.0.0.1"
port "6600"

restore_paused "yes"

#pid_file			"$XDG_RUNTIME_DIR/mpd/mpd.pid"
#pid_file			"~/.mpd/pid"
#sticker_file			"$XDG_CACHE_HOME/sticker.sql"
#sticker_file			"~/.mpd/sticker.sql"

#user				"nobody"
#group				"nogroup"
#bind_to_address		"any"
#bind_to_address		"$XDG_RUNTIME_DIR/mpd/socket"
#bind_to_address		"~/.mpd/socket"
#port				"6600"
#log_level			"notice"
#restore_paused "no"
#save_absolute_paths_in_playlists	"no"
#follow_outside_symlinks	"yes"
#follow_inside_symlinks		"yes"
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}
audio_output {
	type		"pulse"
	name		"pulse audio"
##	server		"remote_server"		# optional
##	sink		"remote_server_sink"	# optional
##	media_role	"media_role"		#optional
}